sudo: required
services:
  - docker

before_install:
  - docker build -t unlmtd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true unlmtd/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-012153171837"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
